import React from "react";
import PropTypes from "prop-types";
import MarryRegistration from "./MarryRegistration";

const MarryPresenter = props => {
  const {
    eventClassification,
    contractDate,
    contractClassification,
    dbPath,
    userName,
    address1,
    address2,
    address3,
    hallName,
    menuName,
    adultCharge,
    childCharge,
    paymentAssuranceCount,
    contractMemo,
    groomName,
    brideName,
    motherNameOfGroom,
    fatherNameOfGroom,
    motherNameOfBride,
    fatherNameOfBride,
    parentGroomRelations,
    parentBrideRelations,
    mobileOfGroom,
    mobileOfBride,
    mobileOfGroom2,
    mobileOfBride2,
    emailOfGroom,
    emailOfBride,
    mealTicketCountOfGroom,
    mealTicketCountOfBride,
    estimatedAttendanceNumbers,
    eventDate,
    eventHour,
    eventMin,
    eventHall,
    eventHalls,
    menus,
    menu,
    users,
    menuPrice,
    paymentDate,
    accountClassification,
    amount,
    paymentClassification,
    paymentMemo
  } = props;
  return (
    <MarryRegistration
      eventClassification={eventClassification}
      contractDate={contractDate}
      contractClassification={contractClassification}
      dbPath={dbPath}
      userName={userName}
      address1={address1}
      address2={address2}
      address3={address3}
      hallName={hallName}
      menuName={menuName}
      adultCharge={adultCharge}
      childCharge={childCharge}
      paymentAssuranceCount={paymentAssuranceCount}
      contractMemo={contractMemo}
      groomName={groomName}
      brideName={brideName}
      motherNameOfGroom={motherNameOfGroom}
      fatherNameOfGroom={fatherNameOfGroom}
      motherNameOfBride={motherNameOfBride}
      fatherNameOfBride={fatherNameOfBride}
      parentGroomRelations={parentGroomRelations}
      parentBrideRelations={parentBrideRelations}
      mobileOfGroom={mobileOfGroom}
      mobileOfBride={mobileOfBride}
      mobileOfGroom2={mobileOfGroom2}
      mobileOfBride2={mobileOfBride2}
      emailOfGroom={emailOfGroom}
      emailOfBride={emailOfBride}
      mealTicketCountOfGroom={mealTicketCountOfGroom}
      mealTicketCountOfBride={mealTicketCountOfBride}
      estimatedAttendanceNumbers={estimatedAttendanceNumbers}
      eventDate={eventDate}
      eventHour={eventHour}
      eventMin={eventMin}
      eventHall={eventHall}
      eventHalls={eventHalls}
      menus={menus}
      menu={menu}
      users={users}
      menuPrice={menuPrice}
      contractClassification={contractClassification}
      paymentDate={paymentDate}
      accountClassification={accountClassification}
      amount={amount}
      paymentClassification={paymentClassification}
      paymentMemo={paymentMemo}
      handleChangeContractDate={props.handleChangeContractDate}
      handleChangeUser={props.handleChangeUser}
      handleChangeContractClassification={
        props.handleChangeContractClassification
      }
      handleChangeDbPath={props.handleChangeDbPath}
      handleChangeAddress1={props.handleChangeAddress1}
      handleChangeAddress2={props.handleChangeAddress2}
      handleChangeAddress3={props.handleChangeAddress3}
      handleChangeEventHall={props.handleChangeEventHall}
      handleChangeEventDate={props.handleChangeEventDate}
      handleChangeEventHour={props.handleChangeEventHour}
      handleChangeEventMin={props.handleChangeEventMin}
      setStartDate={props.setStartDate}
      handleChangeMenu={props.handleChangeMenu}
      handleChangecontractMemo={props.handleChangecontractMemo}
      handleChangeAdultCharge={props.handleChangeAdultCharge}
      handleChangeChildCharge={props.handleChangeChildCharge}
      handleChangePaymentAssuranceCount={
        props.handleChangePaymentAssuranceCount
      }
      handleChangePaymentDate={props.handleChangePaymentDate}
      handleChangePaymentClassification={
        props.handleChangePaymentClassification
      }
      handleChangeAmount={props.handleChangeAmount}
      handleChangeAccountClassification={
        props.handleChangeAccountClassification
      }
      handleChangeContractMemo={props.handleChangeContractMemo}
      handleChangePaymentMemo={props.handleChangePaymentMemo}
      handleChangeGroomName={props.handleChangeGroomName}
      handleChangeBrideName={props.handleChangeBrideName}
      handleChangeMotherNameOfGroom={props.handleChangeMotherNameOfGroom}
      handleChangeFatherNameOfGroom={props.handleChangeFatherNameOfGroom}
      handleChangeMotherNameOfBride={props.handleChangeMotherNameOfBride}
      handleChangeFatherNameOfBride={props.handleChangeFatherNameOfBride}
      handleChangeParentGroomRelations={props.handleChangeParentGroomRelations}
      handleChangeParentBrideRelations={props.handleChangeParentBrideRelations}
      handleChangeMobileOfGroom={props.handleChangeMobileOfGroom}
      handleChangeMobileOfBride={props.handleChangeMobileOfBride}
      handleChangeMobileOfGroom2={props.handleChangeMobileOfGroom2}
      handleChangeMobileOfBride2={props.handleChangeMobileOfBride2}
      handleChangeEmailOfGroom={props.handleChangeEmailOfGroom}
      handleChangeEmailOfBride={props.handleChangeEmailOfBride}
      handleChangeMealTicketCountOfGroom={
        props.handleChangeMealTicketCountOfGroom
      }
      handleChangeMealTicketCountOfBride={
        props.handleChangeMealTicketCountOfBride
      }
      handleChangeEstimatedAttendanceNumbers={
        props.handleChangeEstimatedAttendanceNumbers
      }
      onClickSubmitButton={props.onClickSubmitButton}
    />
  );
};

MarryPresenter.propTypes = {};

export default MarryPresenter;
